# Generated by Django 4.0.6 on 2022-08-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userroles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
