# Generated by Django 4.0.6 on 2022-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_rename_list_id_task_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
