# Generated by Django 4.0.6 on 2022-08-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_subtask',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_list', to='features.tasklist'),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='features.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='features.task')),
            ],
        ),
    ]
