# Generated by Django 4.0.6 on 2022-08-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_task_is_subtask_alter_task_list_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='sub_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='features.task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='features.task'),
        ),
    ]
