# Generated by Django 4.0.6 on 2022-08-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_alter_subtask_sub_task_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='features.tasklist'),
        ),
    ]
